version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules:delegated
    depends_on:
      - postgres14

  postgres14:
    image: postgres:14-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - postgres14:/var/lib/postgresql/data:delegated

volumes:
  node_modules:
  postgres14:
